server:
  port: 8003

spring:
  application:
    name: weatherstationthree

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true