apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weatherapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: weatherapp
        env: prod
        role: web
    spec:
      containers:
      - name: weatherapp
        image: weatherapp:v1
        ports:
        - containerPort: 8080