apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weatherstationtwo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: weatherstationtwo
        env: prod
        role: web
    spec:
      containers:
      - name: weatherstationtwo
        image: weatherstationtwo:v1
        ports:
        - containerPort: 8002