apiVersion: v1
kind: Service
metadata:
  labels:
    app: weatherstationthree
    role: web
    env: prod
  name: weatherstationthree
spec:
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30003
  selector:
    app: weatherstationthree
    role: web
    env: prod
  type: NodePort