apiVersion: v1
kind: Service
metadata:
  labels:
    app: weathercollector
    role: web
    env: prod
  name: weathercollector
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100
  selector:
    app: weathercollector
    role: web
    env: prod
  type: NodePort