server:
  port: 8002

spring:
  application:
    name: weatherstationtwo

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true