apiVersion: v1
kind: Service
metadata:
  labels:
    app: weatherstationone
    role: web
    env: prod
  name: weatherstationone
spec:
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001
  selector:
    app: weatherstationone
    role: web
    env: prod
  type: NodePort