apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weatherstationone
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: weatherstationone
        env: prod
        role: web
    spec:
      containers:
      - name: weatherstationone
        image: weatherstationone:v1
        ports:
        - containerPort: 8001